### ISSUE TITLE
Not all data is being converted

### ISSUE THREAD

**Issue by Artapel** [skippernl/Fortigate2Excel#9]
Howsit, and well done with your work so far.
So far its very simple to use your scripts, but I've noticed that no all data is being converted to excel.

for example, I have 282 VIP (NAT) VirtualIP`s but only 82 of them are written to file.

I tried to re-download the config file, I verified that all 282 VIP entries does exist in the downloaded config file, I re-ran the script pon the same new verified config file, but it only output 82 lines and not the complete 282 lines expected.

Any ideas on this?

**Comment by skippernl** [comment]
Hi,

Not on the top off my head.

Are there any characters in the name of the vips that excel doesn't like?

Are only the first 82 or last 82 lines counted?




Op do 7 nov. 2024 16:51 schreef Artapel ***@***.***>:

**Comment by Artapel** [comment]
Hi

So, interestingly enough, I've noticed that the VIP sheet in Excel contains both virtual server entries and Virtual IP entries.
only the FIRST 52 virtual IP entries and ALL the Virtual Server entries are there.

of the batt, I cannot identify any invalid characters, they all use a standard naming convention across the board,

**Comment by skippernl** [comment]
Can you post a sanitized version with two config segments one for a virtual server and one for a Virtual IP?

I think my script might confuse them.

**Comment by Artapel** [comment]
[config firewall vip.txt](https://github.com/user-attachments/files/17702394/config.firewall.vip.txt)

Thanks please see file

**Comment by skippernl** [comment]
Bug confirmed.

Need some more testing for the fix. Also vip groups are not available now
might try to get this in.

Op ma 11 nov 2024 13:32 schreef Artapel ***@***.***>:

**Comment by Artapel** [comment]
Thank you very much!



Regards
Corné Kruger
IT Manager



-------- Original message --------
From: skippernl ***@***.***>
Date: 2024/11/11 20:12 (GMT+02:00)
To: skippernl/Fortigate2Excel ***@***.***>
Cc: Corne Kruger ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [skippernl/Fortigate2Excel] Not all data is being converted (Issue #9)

**Comment by skippernl** [comment]
I have updated the script should be working now

**Comment by Artapel** [comment]
Well damn done!
I've tested it just now and it ran perfectly, export is good,

Good job and well done! Thank you for your word

**Comment by skippernl** [comment]
issue closed -> Resolved
